### ISSUE TITLE
BlockingCollection.TryTake throws in .NET 2.0 and 3.5

### ISSUE THREAD

**Issue by NN---** [theraot/Theraot#42]
Runnig this:
```cs
			var a = new BlockingCollection<int>();
			a.TryTake(out var _);
```

Returns with exception:
```
System.Threading.SemaphoreFullException : Adding the specified count to the semaphore would cause it to exceed its maximum count.
   at System.Threading.SemaphoreSlim.TryOffset(Int32 releaseCount, Int32& previous) in Theraot\Framework.Core\System\Threading\SemaphoreSlim.net35.cs:line 355
   at System.Threading.SemaphoreSlim.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken) in Theraot\Framework.Core\System\Threading\SemaphoreSlim.net35.cs:line 133
   at System.Collections.Concurrent.BlockingCollection`1.PrivateData.TryTake(T& item, Int32 millisecondsTimeout, CancellationToken cancellationToken) in Theraot\Framework.Core\System\Collections\Concurrent\BlockingCollection.cs:line 594
   at System.Collections.Concurrent.BlockingCollection`1.TryTake(T& item) in Theraot\Framework.Core\System\Collections\Concurrent\BlockingCollection.cs:line 484
```

**Comment by theraot** [comment]
:S

**Comment by NN---** [comment]
Btw, why your variables in SemaphoreSlim are not volatile as .NET does ?
https://referencesource.microsoft.com/#mscorlib/system/threading/SemaphoreSlim.cs,ed5ff10a1fcba4d4

You can compare the implementation from ReferenceSource/System.Threading package/CoreCLR.

**Comment by theraot** [comment]
@NN--- I use Volatile.Read, Volatile.Write, and Interlocked.CompareExchange

Why? Because volatile fields may not work correctly, I just avoid them. They caused me problems in the past.

See [C# - The C# Memory Model in Theory and Practice, Part 2](https://msdn.microsoft.com/en-us/magazine/jj883956.aspx?f=255&MSPPError=-2147217396). Quote:

> In this case, the correct solution is to mark field _A as volatile. If that’s done, the compiler shouldn’t reorder the reads of _A and _B, because the load of _A has load-acquire semantics. However, I should  point out that the .NET Framework, through version 4, **doesn’t handle this case correctly** and, in fact, marking the _A field as volatile will not prevent the read reordering. This issue has been fixed in the .NET Framework version 4.5.
(emphasis mine)

**Comment by NN---** [comment]
Of course volatile doesn't mean you don't need locks.
It just states clearer your intent.

I didn't know about this implementation bug.
Very sad :(

**Comment by theraot** [comment]
Working on this
