### ISSUE TITLE
BlockingCollection.Add generate a 'System.Threading.SemaphoreFullException' 

### ISSUE THREAD

**Issue by ccsheller** [theraot/Theraot#53]
The Stack
```
   at System.Threading.SemaphoreSlim.TryOffset(Int32 releaseCount, Int32& previous)
   at System.Threading.SemaphoreSlim.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Collections.Concurrent.BlockingCollection`1.PrivateData.TryAdd(T item, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Collections.Concurrent.BlockingCollection`1.Add(T item)

```

**Comment by theraot** [comment]
A fix for this is already in the source, I will push a new nuget between today and tomorrow.

**Comment by ccsheller** [comment]
Do you have a replacement code?I'm waiting to use it.

**Comment by theraot** [comment]
@ccsheller nuget 3.0.0-beta2 pushed
